name: "tagged-release"
on:
  push:
    tags:
      - "*"

jobs:
  tagged-release:
    name: "Build & Create a Tagged Release"
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: npm ci

      - name: Build
        run: npm run build --if-present

      - name: Test
        run: npm run test --if-present

      - name: Publish release
        uses: saucal/action-release@main
        with:
          github_token: ${{ secrets.the_token }}